### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by SrTobi** [SrTobi/futures-scopes#1]
Encountered this randomly while running tests... was not able to reproduce it yet.

```
     Running tests/relay_scope.rs (target/debug/deps/relay_scope-b5e0eb5128ecc476)

running 12 tests
test relay::test_drop_without_spawner ... ok
test relay::test_on_local_pool ... ok
test relay::test_pool_drop ... ok
test relay::test_futures_are_dropped ... ok
test relay::test_spawner_status ... ok
test relay::test_can_continue_after_panic ... ok
test relay::test_run_on_multiple_pools ... ok
test relay::test_mutate_outer ... ok
test relay::test_panic_in_spawned ... ok
test relay::test_waiting ... ok
test relay::test_example ... ok
thread '<unnamed>' panicked at 'attempt to subtract with overflow', src/relay/relay_pad.rs:122:30
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/tobi/workspace/srtobi/futures-scopes/src/relay/relay_future.rs:209:57
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/tobi/workspace/srtobi/futures-scopes/src/relay/relay_future.rs:209:57
thread '<unnamed>' panicked at 'attempt to subtract with overflow', src/relay/relay_pad.rs:122:30
stack backtrace:
   0:     0x562a81d91901 - std::backtrace_rs::backtrace::libunwind::trace::h66dc1c6acf794faa
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x562a81d91901 - std::backtrace_rs::backtrace::trace_unsynchronized::ha80d20099a67f790
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x562a81d91901 - std::sys_common::backtrace::_print_fmt::h7b959d43f35f16d4
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x562a81d91901 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hdaa196410d9ee0b9
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x562a81dbbcef - core::fmt::rt::Argument::fmt::h0ddfbbe8be3f80d0
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/fmt/rt.rs:138:9
   5:     0x562a81dbbcef - core::fmt::write::h66b3c629f3d623e4
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/fmt/mod.rs:1094:21
   6:     0x562a81d8e497 - std::io::Write::write_fmt::hc3b13ee21464b781
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/io/mod.rs:1714:15
   7:     0x562a81d91715 - std::sys_common::backtrace::_print::h1a49cfb0cf3cce17
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x562a81d91715 - std::sys_common::backtrace::print::hca95c2d0055e42a2
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x562a81d933a3 - std::panicking::default_hook::{{closure}}::hc03c01c56bca600c
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:269:22
  10:     0x562a81d930c0 - std::panicking::default_hook::hb2cb5315b6634f1c
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:285:9
  11:     0x562a81cd8352 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h4420a0bfee50bab5
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/alloc/src/boxed.rs:2007:9
  12:     0x562a81cd8352 - test::test_main::{{closure}}::h767aa51a64937811
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/test/src/lib.rs:135:21
  13:     0x562a81d93a9e - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hb3a915ffd78277c6
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/alloc/src/boxed.rs:2007:9
  14:     0x562a81d93a9e - std::panicking::rust_panic_with_hook::h75cd912a39a34e8a
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:709:13
  15:     0x562a81d937e1 - std::panicking::begin_panic_handler::{{closure}}::h1498b46f7849e167
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:595:13
  16:     0x562a81d91d66 - std::sys_common::backtrace::__rust_end_short_backtrace::hd36a39b27b98086b
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:151:18
  17:     0x562a81d93572 - rust_begin_unwind
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:593:5
  18:     0x562a81c884d3 - core::panicking::panic_fmt::h98ef273141454c23
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:67:14
  19:     0x562a81c88563 - core::panicking::panic::hf53fd8b0bfa5848e
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:117:5
  20:     0x562a81cf5bdb - futures_scopes::relay::relay_pad::RelayPad::end_future_polling::h568fcdd603e7a466
                               at /home/tobi/workspace/srtobi/futures-scopes/src/relay/relay_pad.rs:122:30
  21:     0x562a81cf2168 - <futures_scopes::relay::relay_pad::FuturePollingGuard as core::ops::drop::Drop>::drop::h6e6ca858fce67bfb
                               at /home/tobi/workspace/srtobi/futures-scopes/src/relay/relay_pad.rs:200:9
  22:     0x562a81cee3fb - core::ptr::drop_in_place<futures_scopes::relay::relay_pad::FuturePollingGuard>::h95bc305f35b93a65
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/ptr/mod.rs:497:1
  23:     0x562a81c9bc59 - <futures_scopes::relay::relay_future::RelayFuture<Sp> as core::future::future::Future>::poll::h148829e3d9aa6d10
                               at /home/tobi/workspace/srtobi/futures-scopes/src/relay/relay_future.rs:251:17
  24:     0x562a81c9d013 - <futures_scopes::relay::relay_future::UnsafeRelayFuture<Sp> as core::future::future::Future>::poll::h41e3b43f4b39889f
                               at /home/tobi/workspace/srtobi/futures-scopes/src/relay/relay_future.rs:308:9
  25:     0x562a81d4e17d - <futures_task::future_obj::LocalFutureObj<T> as core::future::future::Future>::poll::h4a5b27bbd113fd50
                               at /home/tobi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-task-0.3.28/src/future_obj.rs:84:18
  26:     0x562a81d4e126 - <futures_task::future_obj::FutureObj<T> as core::future::future::Future>::poll::h6cd086c926c279be
                               at /home/tobi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-task-0.3.28/src/future_obj.rs:127:9
  27:     0x562a81d4bbb3 - futures_util::future::future::FutureExt::poll_unpin::h2843b55984314d23
                               at /home/tobi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/future/mod.rs:562:9
  28:     0x562a81d5119e - futures_executor::thread_pool::Task::run::h21071e553715512a
                               at /home/tobi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-executor-0.3.28/src/thread_pool.rs:325:27
  29:     0x562a81d50188 - futures_executor::thread_pool::PoolState::work::ha018b50b445c1521
                               at /home/tobi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-executor-0.3.28/src/thread_pool.rs:157:39
  30:     0x562a81d51017 - futures_executor::thread_pool::ThreadPoolBuilder::create::{{closure}}::h95b2062c5f88f6ca
                               at /home/tobi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-executor-0.3.28/src/thread_pool.rs:287:42
  31:     0x562a81d2f859 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3faba87d92c257c1
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:135:18
  32:     0x562a81d37581 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::h512fd3aa46470b70
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/thread/mod.rs:529:17
  33:     0x562a81d4e5d1 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::ha4f345b66ef3ea44
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panic/unwind_safe.rs:271:9
  34:     0x562a81d4eb4a - std::panicking::try::do_call::h862868acbf46d4ca
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:500:40
  35:     0x562a81d516fb - __rust_try
  36:     0x562a81d4e95f - std::panicking::try::hf6a03c4d338da265
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:464:19
  37:     0x562a81d373a1 - std::panic::catch_unwind::h00ba7d166b071b5e
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panic.rs:142:14
  38:     0x562a81d373a1 - std::thread::Builder::spawn_unchecked_::{{closure}}::hc481bba9803c99b4
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/thread/mod.rs:528:30
  39:     0x562a81d4964f - core::ops::function::FnOnce::call_once{{vtable.shim}}::hc576f0262feb1b62
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/ops/function.rs:250:5
  40:     0x562a81d97fe5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hde6e666388faa495
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/alloc/src/boxed.rs:1993:9
  41:     0x562a81d97fe5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h9b6389e489a4842f
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/alloc/src/boxed.rs:1993:9
  42:     0x562a81d97fe5 - std::sys::unix::thread::Thread::new::thread_start::hcab660740b858b1f
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys/unix/thread.rs:108:17
  43:     0x7f9a63124dd4 - start_thread
  44:     0x7f9a631a69b0 - __clone3
  45:                0x0 - <unknown>
thread '<unnamed>' panicked at 'panic in a function that cannot unwind', library/core/src/panicking.rs:126:5
stack backtrace:
   0:     0x562a81d91901 - std::backtrace_rs::backtrace::libunwind::trace::h66dc1c6acf794faa
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x562a81d91901 - std::backtrace_rs::backtrace::trace_unsynchronized::ha80d20099a67f790
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x562a81d91901 - std::sys_common::backtrace::_print_fmt::h7b959d43f35f16d4
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x562a81d91901 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hdaa196410d9ee0b9
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x562a81dbbcef - core::fmt::rt::Argument::fmt::h0ddfbbe8be3f80d0
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/fmt/rt.rs:138:9
   5:     0x562a81dbbcef - core::fmt::write::h66b3c629f3d623e4
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/fmt/mod.rs:1094:21
   6:     0x562a81d8e397 - std::io::Write::write_fmt::hb6d80fba4115e0c2
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/io/mod.rs:1714:15
   7:     0x562a81d91715 - std::sys_common::backtrace::_print::h1a49cfb0cf3cce17
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x562a81d91715 - std::sys_common::backtrace::print::hca95c2d0055e42a2
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x562a81d933a3 - std::panicking::default_hook::{{closure}}::hc03c01c56bca600c
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:269:22
  10:     0x562a81d93134 - std::panicking::default_hook::hb2cb5315b6634f1c
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:288:9
  11:     0x562a81cd8352 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h4420a0bfee50bab5
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/alloc/src/boxed.rs:2007:9
  12:     0x562a81cd8352 - test::test_main::{{closure}}::h767aa51a64937811
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/test/src/lib.rs:135:21
  13:     0x562a81d93a9e - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hb3a915ffd78277c6
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/alloc/src/boxed.rs:2007:9
  14:     0x562a81d93a9e - std::panicking::rust_panic_with_hook::h75cd912a39a34e8a
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:709:13
  15:     0x562a81d937e1 - std::panicking::begin_panic_handler::{{closure}}::h1498b46f7849e167
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:595:13
  16:     0x562a81d91d66 - std::sys_common::backtrace::__rust_end_short_backtrace::hd36a39b27b98086b
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:151:18
  17:     0x562a81d93572 - rust_begin_unwind
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:593:5
  18:     0x562a81c88513 - core::panicking::panic_nounwind_fmt::hd751fcb82a791f5b
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:96:14
  19:     0x562a81c885b7 - core::panicking::panic_nounwind::hc62d0ba7772d7051
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:126:5
  20:     0x562a81c88743 - core::panicking::panic_cannot_unwind::ha2a820cb42f0ce8a
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:189:5
  21:     0x562a81c9bef3 - <futures_scopes::relay::relay_future::RelayFuture<Sp> as core::future::future::Future>::poll::h148829e3d9aa6d10
                               at /home/tobi/workspace/srtobi/futures-scopes/src/relay/relay_future.rs:204:5
  22:     0x562a81c9d013 - <futures_scopes::relay::relay_future::UnsafeRelayFuture<Sp> as core::future::future::Future>::poll::h41e3b43f4b39889f
                               at /home/tobi/workspace/srtobi/futures-scopes/src/relay/relay_future.rs:308:9
  23:     0x562a81d4e17d - <futures_task::future_obj::LocalFutureObj<T> as core::future::future::Future>::poll::h4a5b27bbd113fd50
                               at /home/tobi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-task-0.3.28/src/future_obj.rs:84:18
  24:     0x562a81d4e126 - <futures_task::future_obj::FutureObj<T> as core::future::future::Future>::poll::h6cd086c926c279be
                               at /home/tobi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-task-0.3.28/src/future_obj.rs:127:9
  25:     0x562a81d4bbb3 - futures_util::future::future::FutureExt::poll_unpin::h2843b55984314d23
                               at /home/tobi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/future/mod.rs:562:9
  26:     0x562a81d5119e - futures_executor::thread_pool::Task::run::h21071e553715512a
                               at /home/tobi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-executor-0.3.28/src/thread_pool.rs:325:27
  27:     0x562a81d50188 - futures_executor::thread_pool::PoolState::work::ha018b50b445c1521
                               at /home/tobi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-executor-0.3.28/src/thread_pool.rs:157:39
  28:     0x562a81d51017 - futures_executor::thread_pool::ThreadPoolBuilder::create::{{closure}}::h95b2062c5f88f6ca
                               at /home/tobi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-executor-0.3.28/src/thread_pool.rs:287:42
  29:     0x562a81d2f859 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3faba87d92c257c1
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:135:18
  30:     0x562a81d37581 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::h512fd3aa46470b70
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/thread/mod.rs:529:17
  31:     0x562a81d4e5d1 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::ha4f345b66ef3ea44
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panic/unwind_safe.rs:271:9
  32:     0x562a81d4eb4a - std::panicking::try::do_call::h862868acbf46d4ca
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:500:40
  33:     0x562a81d516fb - __rust_try
  34:     0x562a81d4e95f - std::panicking::try::hf6a03c4d338da265
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:464:19
  35:     0x562a81d373a1 - std::panic::catch_unwind::h00ba7d166b071b5e
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panic.rs:142:14
  36:     0x562a81d373a1 - std::thread::Builder::spawn_unchecked_::{{closure}}::hc481bba9803c99b4
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/thread/mod.rs:528:30
  37:     0x562a81d4964f - core::ops::function::FnOnce::call_once{{vtable.shim}}::hc576f0262feb1b62
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/ops/function.rs:250:5
  38:     0x562a81d97fe5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hde6e666388faa495
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/alloc/src/boxed.rs:1993:9
  39:     0x562a81d97fe5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h9b6389e489a4842f
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/alloc/src/boxed.rs:1993:9
  40:     0x562a81d97fe5 - std::sys::unix::thread::Thread::new::thread_start::hcab660740b858b1f
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys/unix/thread.rs:108:17
  41:     0x7f9a63124dd4 - start_thread
  42:     0x7f9a631a69b0 - __clone3
  43:                0x0 - <unknown>
thread caused non-unwinding panic. aborting.
error: test failed, to rerun pass `--test relay_scope`

Caused by:
  process didn't exit successfully: `/home/tobi/workspace/srtobi/futures-scopes/target/debug/deps/relay_scope-b5e0eb5128ecc476` (signal: 6, SIGABRT: process abort signal)
```

**Comment by SrTobi** [comment]
Probably fixed by the fix for #3
